### ISSUE TITLE
When Show in IDE opens new file in vim, ft is not applied

### ISSUE THREAD

**Issue by maximilianriemensberger** [CoatiSoftware/vim-sourcetrail#2]
Happens for me on VimR 0.23.0 with neovim on Mac OS High Sierra

Reproduce:
* connect sourcetrail to vim (:SourcetrailActivateToken)
* no files open in vim
* navigate to some function definition
* CMD+Left click on function name

Result:
Opens file in vim, but no filetype, syntax highlighting, etc. are applied.

Expected:
Open file in vim with filetype and everything else applied (equivalent to :e filename)

Current workaround:
Enter :e in vim after switching windows to force the filetype redetection

**Comment by egraether** [comment]
Took a quick look into the code. We already use the e command:
https://github.com/CoatiSoftware/vim-sourcetrail/blob/d0514fd6bc4551086b3585019fe2c6839a9df9fd/autoload/sourcetrail.py#L198

I will try if I can reproduce this.

**Comment by maximilianriemensberger** [comment]
I think I found a fix that works for me ...

Add `nested` to autocommand that calls `:e!` to force generating all relevant events like `BufRead`, etc. [vim-sourcetrail/autoload/sourcetrail.vim](https://github.com/CoatiSoftware/vim-sourcetrail/blob/master/autoload/sourcetrail.vim)
```diff
if has('python')
	augroup SourcetrailPlugin
-		autocmd FocusGained,BufEnter	* :call sourcetrail#UpdateBuffer()
+		autocmd FocusGained,BufEnter	* nested :call sourcetrail#UpdateBuffer()
		autocmd VimLeavePre				* :call sourcetrail#SourcetrailShutdown()
	augroup END
endif
```

Reorder the update flag to avoid recursion [vim-sourcetrail/autoload/sourcetrail.py](https://github.com/CoatiSoftware/vim-sourcetrail/blob/master/autoload/sourcetrail.py)
```diff
+                cls.inst().__update = False
                 vim.command("e! " + cls.inst().__file)
                 vim.current.window.cursor = (cls.inst().__row, cls.inst().__col)
-                cls.inst().__update = False
```

**Comment by maximilianriemensberger** [comment]
The relevant section of the vim manual: http://vimdoc.sourceforge.net/htmldoc/autocmd.html#autocmd-nested

**Comment by maximilianriemensberger** [comment]
And I think that it should be  `has('python') || has('python3')` in [vim-sourcetrail/autoload/sourcetrail.vim](https://github.com/CoatiSoftware/vim-sourcetrail/blob/master/autoload/sourcetrail.vim#109)

**Comment by egraether** [comment]
The original author of this plugin is unfortunately not with us anymore, so I would need to read into all of it first. Would you like to put together a pull request please?

**Comment by maximilianriemensberger** [comment]
Sure

**Comment by egraether** [comment]
Thank you very much!
