### ISSUE TITLE
Socket in use

### ISSUE THREAD

**Issue by austinmw** [CoatiSoftware/vim-sourcetrail#4]
Hi, I don't know if this project is still maintained, but I'm getting an error using with mac/spacevim. sourcetrail will open to a location with `SourcetrailActivateToken`, but I constantly get this popup in vim:

```
Socket needed for Sourcetrail plugin already in use
Current Position sent to Sourcetrail
Press ENTER or type command to continue
```
Is there any way to determine why this is or suppress it?

**Comment by egraether** [comment]
Apparently the desired ports are already in use. You need to change them in the Plugin (see [sourcetrail.vim](https://github.com/CoatiSoftware/vim-sourcetrail/blob/master/autoload/sourcetrail.vim#L42)) and in Sourcetrail's Preferences (Plugin -> Sourcetrail & Plugin Port). Then it should work.
